-- 1. Application and database roles
GRANT APPLICATION ROLE SNOWFLAKE.AI_OBSERVABILITY_EVENTS_LOOKUP
TO ROLE ROLE_UMESHAREVELATOR;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER
TO ROLE ROLE_UMESHAREVELATOR;

-- 2. Database-level privileges
GRANT ALL PRIVILEGES ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;

-- 3. Schema-level privileges (all schemas)
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.RAW TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.CURATED TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.SEARCH TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.ANALYTICS TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.ADMIN TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.INGESTION TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.APP TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.DATA TO ROLE ROLE_UMESHAREVELATOR;

-- 4. All object privileges (existing + future) across all schemas
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL STREAMS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE ROLE_UMESHAREVELATOR;

-- 5. Notebooks (all schemas)
GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE ROLE_UMESHAREVELATOR;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE ROLE_UMESHAREVELATOR;
GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA SNOWFLAKE_INTELLIGENCE.DATA TO ROLE ROLE_UMESHAREVELATOR;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA SNOWFLAKE_INTELLIGENCE.DATA TO ROLE ROLE_UMESHAREVELATOR;

-- 6. Snowflake Intelligence object
CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE ROLE_UMESHAREVELATOR;
