USE ROLE ROLE_UMESHAREVELATOR;
USE DATABASE SNOWFLAKE_INTELLIGENCE;
USE SCHEMA RAW;

CREATE OR REPLACE MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.EMAIL_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_UMESHAREVELATOR' THEN val
        WHEN val IS NULL THEN NULL
        ELSE LEFT(val, 2) || '***@' || SPLIT_PART(val, '@', 2)
    END;

CREATE OR REPLACE MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.PHONE_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_UMESHAREVELATOR' THEN val
        WHEN val IS NULL THEN NULL
        ELSE '***-' || RIGHT(val, 4)
    END;

CREATE OR REPLACE MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.TEXT_PII_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_UMESHAREVELATOR' THEN val
        ELSE 'REDACTED'
    END;

ALTER TABLE SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS
    MODIFY COLUMN EMAIL SET MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.EMAIL_MASK;

ALTER TABLE SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS
    MODIFY COLUMN PHONE SET MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.PHONE_MASK;

ALTER TABLE SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS
    MODIFY COLUMN MOBILE SET MASKING POLICY SNOWFLAKE_INTELLIGENCE.RAW.PHONE_MASK;
