CREATE ROLE IF NOT EXISTS SI_ADMIN;
CREATE ROLE IF NOT EXISTS SI_USER;
CREATE ROLE IF NOT EXISTS SI_INGESTION;
CREATE ROLE IF NOT EXISTS SI_AGENT;

GRANT ROLE SI_USER TO ROLE SI_ADMIN;
GRANT ROLE SI_INGESTION TO ROLE SI_ADMIN;
GRANT ROLE SI_AGENT TO ROLE SI_ADMIN;
GRANT ROLE SI_ADMIN TO ROLE ROLE_UMESHAREVELATOR;

GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_USER;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_INGESTION;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_AGENT;

GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_INGESTION;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SI_AGENT;

GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_INTELLIGENCE.CURATED TO ROLE SI_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_INTELLIGENCE.ANALYTICS TO ROLE SI_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_INTELLIGENCE.ADMIN TO ROLE SI_USER;

GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.RAW TO ROLE SI_INGESTION;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.CURATED TO ROLE SI_INGESTION;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.INGESTION TO ROLE SI_INGESTION;

GRANT USAGE ON WAREHOUSE AI_WH TO ROLE SI_INGESTION;
GRANT USAGE ON WAREHOUSE AI_WH TO ROLE SI_AGENT;
GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE SI_USER;
GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE SI_ADMIN;
