USE DATABASE SNOWFLAKE_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.RAW;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.CURATED;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.SEARCH;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.ADMIN;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.INGESTION;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.APP;
