CREATE OR REPLACE SECRET SNOWFLAKE_INTELLIGENCE.INGESTION.GITBOOK_API_SECRET
    TYPE = GENERIC_STRING
    SECRET_STRING = '<GITBOOK_API_KEY>';

CREATE OR REPLACE NETWORK RULE SNOWFLAKE_INTELLIGENCE.INGESTION.GITBOOK_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('api.gitbook.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SI_GITBOOK_ACCESS
    ALLOWED_NETWORK_RULES = (SNOWFLAKE_INTELLIGENCE.INGESTION.GITBOOK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (SNOWFLAKE_INTELLIGENCE.INGESTION.GITBOOK_API_SECRET)
    ENABLED = TRUE;

CREATE OR REPLACE NOTIFICATION INTEGRATION SI_EMAIL_NOTIFICATIONS
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('admin@revelator.com');
