-- Secret already exists: SNOWFLAKE_INTELLIGENCE.INGESTION.FRESHDESK_API_SECRET
-- Verify: DESCRIBE SECRET SNOWFLAKE_INTELLIGENCE.INGESTION.FRESHDESK_API_SECRET;

CREATE OR REPLACE NETWORK RULE SNOWFLAKE_INTELLIGENCE.INGESTION.FRESHDESK_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = (
        'newaccount1623084859360.freshdesk.com',
        'helpdesk.revelator.com'
    );

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SI_FRESHDESK_ACCESS
    ALLOWED_NETWORK_RULES = (SNOWFLAKE_INTELLIGENCE.INGESTION.FRESHDESK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (SNOWFLAKE_INTELLIGENCE.INGESTION.FRESHDESK_API_SECRET)
    ENABLED = TRUE;
