USE WAREHOUSE AI_WH;
USE DATABASE SNOWFLAKE_INTELLIGENCE;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ADMIN.FRESHDESK_INGESTION_HEALTH AS
WITH latest_runs AS (
    SELECT
        SOURCE_SYSTEM,
        INGESTION_TYPE,
        STARTED_AT,
        COMPLETED_AT,
        RECORDS_INGESTED,
        STATUS,
        ERROR_MESSAGE,
        ROW_NUMBER() OVER (PARTITION BY SOURCE_SYSTEM ORDER BY STARTED_AT DESC) AS rn
    FROM SNOWFLAKE_INTELLIGENCE.INGESTION.INGESTION_LOG
    WHERE SOURCE_SYSTEM ILIKE 'freshdesk%'
),
last_success AS (
    SELECT
        SOURCE_SYSTEM,
        MAX(COMPLETED_AT) AS LAST_SUCCESS_AT
    FROM SNOWFLAKE_INTELLIGENCE.INGESTION.INGESTION_LOG
    WHERE SOURCE_SYSTEM ILIKE 'freshdesk%'
      AND STATUS = 'success'
    GROUP BY SOURCE_SYSTEM
),
table_counts AS (
    SELECT 'FRESHDESK_TICKETS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS
    UNION ALL SELECT 'FRESHDESK_CONTACTS', COUNT(*) FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS
    UNION ALL SELECT 'FRESHDESK_AGENTS', COUNT(*) FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS
    UNION ALL SELECT 'FRESHDESK_COMPANIES', COUNT(*) FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_COMPANIES
    UNION ALL SELECT 'FRESHDESK_TICKET_CONVERSATIONS', COUNT(*) FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKET_CONVERSATIONS
)
SELECT
    lr.SOURCE_SYSTEM,
    lr.INGESTION_TYPE,
    lr.STATUS AS LAST_RUN_STATUS,
    lr.STARTED_AT AS LAST_RUN_STARTED,
    lr.COMPLETED_AT AS LAST_RUN_COMPLETED,
    lr.RECORDS_INGESTED AS LAST_RUN_RECORDS,
    lr.ERROR_MESSAGE AS LAST_RUN_ERROR,
    ls.LAST_SUCCESS_AT,
    DATEDIFF('hour', ls.LAST_SUCCESS_AT, CURRENT_TIMESTAMP()) AS HOURS_SINCE_SUCCESS,
    OBJECT_AGG(tc.TABLE_NAME, tc.ROW_COUNT::VARIANT) AS RAW_TABLE_COUNTS,
    CASE
        WHEN ls.LAST_SUCCESS_AT IS NULL THEN 'CRITICAL'
        WHEN DATEDIFF('hour', ls.LAST_SUCCESS_AT, CURRENT_TIMESTAMP()) < 12 AND lr.STATUS = 'success' THEN 'HEALTHY'
        WHEN DATEDIFF('hour', ls.LAST_SUCCESS_AT, CURRENT_TIMESTAMP()) < 24 THEN 'WARNING'
        ELSE 'CRITICAL'
    END AS HEALTH_STATUS
FROM latest_runs lr
LEFT JOIN last_success ls ON lr.SOURCE_SYSTEM = ls.SOURCE_SYSTEM
CROSS JOIN table_counts tc
WHERE lr.rn = 1
GROUP BY
    lr.SOURCE_SYSTEM,
    lr.INGESTION_TYPE,
    lr.STATUS,
    lr.STARTED_AT,
    lr.COMPLETED_AT,
    lr.RECORDS_INGESTED,
    lr.ERROR_MESSAGE,
    ls.LAST_SUCCESS_AT;

CREATE OR REPLACE ALERT SNOWFLAKE_INTELLIGENCE.ADMIN.FRESHDESK_INGESTION_FAILURE_ALERT
    WAREHOUSE = AI_WH
    SCHEDULE = '60 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM (
            SELECT
                SOURCE_SYSTEM,
                STATUS,
                ROW_NUMBER() OVER (PARTITION BY SOURCE_SYSTEM ORDER BY STARTED_AT DESC) AS rn
            FROM SNOWFLAKE_INTELLIGENCE.INGESTION.INGESTION_LOG
            WHERE SOURCE_SYSTEM ILIKE 'freshdesk%'
        )
        WHERE rn = 1
          AND STATUS != 'success'
    ))
    THEN
        CALL SYSTEM$SEND_EMAIL(
            'SI_EMAIL_NOTIFICATIONS',
            'admin@revelator.com',
            'RevSearch: Freshdesk Ingestion Failure Detected',
            'One or more Freshdesk ingestion pipelines failed in their last run. Check ADMIN.FRESHDESK_INGESTION_HEALTH for details.'
        );

ALTER ALERT SNOWFLAKE_INTELLIGENCE.ADMIN.FRESHDESK_INGESTION_FAILURE_ALERT RESUME;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ADMIN.FRESHDESK_DATA_FRESHNESS AS
SELECT 'FRESHDESK_TICKETS' AS TABLE_NAME,
       COUNT(*) AS ROW_COUNT,
       MAX(_LOADED_AT) AS MAX_LOADED_AT,
       MAX(UPDATED_AT) AS MAX_UPDATED_AT,
       DATEDIFF('hour', MAX(_LOADED_AT), CURRENT_TIMESTAMP()) AS LOADED_STALENESS_HOURS,
       DATEDIFF('hour', MAX(UPDATED_AT), CURRENT_TIMESTAMP()) AS DATA_STALENESS_HOURS
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS
UNION ALL
SELECT 'FRESHDESK_CONTACTS', COUNT(*), MAX(_LOADED_AT), MAX(UPDATED_AT),
       DATEDIFF('hour', MAX(_LOADED_AT), CURRENT_TIMESTAMP()),
       DATEDIFF('hour', MAX(UPDATED_AT), CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS
UNION ALL
SELECT 'FRESHDESK_AGENTS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS
UNION ALL
SELECT 'FRESHDESK_COMPANIES', COUNT(*), MAX(_LOADED_AT), MAX(UPDATED_AT),
       DATEDIFF('hour', MAX(_LOADED_AT), CURRENT_TIMESTAMP()),
       DATEDIFF('hour', MAX(UPDATED_AT), CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_COMPANIES
UNION ALL
SELECT 'FRESHDESK_TICKET_CONVERSATIONS', COUNT(*), MAX(_LOADED_AT), MAX(UPDATED_AT),
       DATEDIFF('hour', MAX(_LOADED_AT), CURRENT_TIMESTAMP()),
       DATEDIFF('hour', MAX(UPDATED_AT), CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKET_CONVERSATIONS
UNION ALL
SELECT 'FRESHDESK_GROUPS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_GROUPS
UNION ALL
SELECT 'FRESHDESK_ROLES', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_ROLES
UNION ALL
SELECT 'FRESHDESK_SOLUTION_CATEGORIES', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_SOLUTION_CATEGORIES
UNION ALL
SELECT 'FRESHDESK_SOLUTION_FOLDERS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_SOLUTION_FOLDERS
UNION ALL
SELECT 'FRESHDESK_SOLUTION_ARTICLES', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_SOLUTION_ARTICLES
UNION ALL
SELECT 'FRESHDESK_DISCUSSION_CATEGORIES', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_DISCUSSION_CATEGORIES
UNION ALL
SELECT 'FRESHDESK_DISCUSSION_FORUMS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_DISCUSSION_FORUMS
UNION ALL
SELECT 'FRESHDESK_DISCUSSION_TOPICS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_DISCUSSION_TOPICS
UNION ALL
SELECT 'FRESHDESK_DISCUSSION_COMMENTS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_DISCUSSION_COMMENTS
UNION ALL
SELECT 'FRESHDESK_SATISFACTION_RATINGS', COUNT(*), NULL, MAX(UPDATED_AT)::TIMESTAMP_NTZ,
       NULL,
       DATEDIFF('hour', MAX(UPDATED_AT)::TIMESTAMP_NTZ, CURRENT_TIMESTAMP())
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_SATISFACTION_RATINGS;
