CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK
    WAREHOUSE = AI_WH
    SCHEDULE = 'USING CRON 0 */6 * * * UTC'
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    ALLOW_OVERLAPPING_EXECUTION = FALSE
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_FRESHDESK();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_SOLUTIONS
    WAREHOUSE = AI_WH
    AFTER SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_FRESHDESK_SOLUTIONS();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_DISCUSSIONS
    WAREHOUSE = AI_WH
    AFTER SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_FRESHDESK_DISCUSSIONS();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_ADMIN
    WAREHOUSE = AI_WH
    AFTER SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_FRESHDESK_ADMIN();

ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_SOLUTIONS RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_DISCUSSIONS RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK_ADMIN RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_FRESHDESK RESUME;
