CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_GITBOOK
    WAREHOUSE = AI_WH
    SCHEDULE = 'USING CRON 0 3 */5 * * America/Los_Angeles'
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_GITBOOK();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_PROCESS_DOCUMENTS
    WAREHOUSE = AI_WH
    AFTER SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_GITBOOK
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.PROCESS_DOCUMENTS();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_CLASSIFY_DOCUMENTS
    WAREHOUSE = AI_WH
    AFTER SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_PROCESS_DOCUMENTS
AS
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.CLASSIFY_DOCUMENTS();

CREATE OR REPLACE TASK SNOWFLAKE_INTELLIGENCE.INGESTION.FULL_REFRESH
    WAREHOUSE = AI_WH
    SCHEDULE = 'USING CRON 0 2 1,15 * * America/Los_Angeles'
AS
BEGIN
    TRUNCATE TABLE SNOWFLAKE_INTELLIGENCE.RAW.GITBOOK_SPACES;
    TRUNCATE TABLE SNOWFLAKE_INTELLIGENCE.RAW.GITBOOK_PAGES;
    TRUNCATE TABLE SNOWFLAKE_INTELLIGENCE.RAW.GITBOOK_COLLECTIONS;
    TRUNCATE TABLE SNOWFLAKE_INTELLIGENCE.CURATED.DOCUMENTS;
    TRUNCATE TABLE SNOWFLAKE_INTELLIGENCE.CURATED.DOCUMENT_CHUNKS;
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.INGEST_GITBOOK();
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.PROCESS_DOCUMENTS();
    CALL SNOWFLAKE_INTELLIGENCE.INGESTION.CLASSIFY_DOCUMENTS();
END;

ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_CLASSIFY_DOCUMENTS RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_PROCESS_DOCUMENTS RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.TASK_INGEST_GITBOOK RESUME;
ALTER TASK SNOWFLAKE_INTELLIGENCE.INGESTION.FULL_REFRESH RESUME;
