USE DATABASE SNOWFLAKE_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.TICKET_TRENDS AS
SELECT
    DATE_TRUNC('WEEK', TRY_TO_TIMESTAMP_TZ(t.CREATED_AT)) AS WEEK,
    COUNT(*) AS TOTAL_TICKETS,
    COUNT(CASE WHEN t.STATUS IN (2, 3) THEN 1 END) AS OPEN_TICKETS,
    COUNT(CASE WHEN t.STATUS IN (4, 5) THEN 1 END) AS RESOLVED_TICKETS,
    AVG(t.PRIORITY) AS AVG_PRIORITY
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t
GROUP BY DATE_TRUNC('WEEK', TRY_TO_TIMESTAMP_TZ(t.CREATED_AT));

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.AGENT_PERFORMANCE_V AS
SELECT
    a.ID AS AGENT_ID,
    PARSE_JSON(a.CONTACT):name::STRING AS AGENT_NAME,
    COUNT(DISTINCT t.ID) AS TICKETS_HANDLED,
    COUNT(DISTINCT CASE WHEN t.STATUS IN (4, 5) THEN t.ID END) AS TICKETS_RESOLVED,
    AVG(CASE
        WHEN t.STATUS IN (4, 5)
        THEN DATEDIFF('HOUR', TRY_TO_TIMESTAMP_TZ(t.CREATED_AT), TRY_TO_TIMESTAMP_TZ(t.UPDATED_AT))
    END) AS AVG_RESOLUTION_HOURS,
    COUNT(DISTINCT c.ID) AS TOTAL_CONVERSATIONS
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS a
LEFT JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t
    ON t.RESPONDER_ID = a.ID
LEFT JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKET_CONVERSATIONS c
    ON c.USER_ID = a.ID
GROUP BY a.ID, PARSE_JSON(a.CONTACT):name::STRING;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.SLA_COMPLIANCE AS
SELECT
    t.ID AS TICKET_ID,
    t.SUBJECT,
    t.PRIORITY,
    t.STATUS,
    TRY_TO_TIMESTAMP_TZ(t.DUE_BY) AS DUE_BY,
    TRY_TO_TIMESTAMP_TZ(t.FR_DUE_BY) AS FR_DUE_BY,
    TRY_TO_TIMESTAMP_TZ(t.CREATED_AT) AS CREATED_AT,
    CASE
        WHEN CURRENT_TIMESTAMP() > TRY_TO_TIMESTAMP_TZ(t.DUE_BY) AND t.STATUS NOT IN (4, 5) THEN TRUE
        ELSE FALSE
    END AS IS_OVERDUE,
    DATEDIFF('HOUR', CURRENT_TIMESTAMP(), TRY_TO_TIMESTAMP_TZ(t.DUE_BY)) AS HOURS_REMAINING
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.CUSTOMER_INSIGHTS AS
SELECT
    co.ID AS COMPANY_ID,
    co.NAME AS COMPANY_NAME,
    COUNT(DISTINCT t.ID) AS TOTAL_TICKETS,
    COUNT(DISTINCT CASE WHEN t.STATUS IN (2, 3) THEN t.ID END) AS OPEN_TICKETS,
    AVG(t.PRIORITY) AS AVG_PRIORITY,
    COUNT(DISTINCT ct.ID) AS TOTAL_CONTACTS,
    MAX(TRY_TO_TIMESTAMP_TZ(t.CREATED_AT)) AS LATEST_TICKET_DATE
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_COMPANIES co
LEFT JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t
    ON t.COMPANY_ID = co.ID
LEFT JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_CONTACTS ct
    ON ct.COMPANY_ID = co.ID
GROUP BY co.ID, co.NAME;
