USE DATABASE SNOWFLAKE_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE SNOWFLAKE_INTELLIGENCE.ANALYTICS.AGENT_DIRECTORY AS
SELECT
    a.ID AS AGENT_ID,
    PARSE_JSON(a.CONTACT):name::VARCHAR AS AGENT_NAME,
    PARSE_JSON(a.CONTACT):email::VARCHAR AS AGENT_EMAIL,
    a.TYPE AS AGENT_TYPE,
    COALESCE(grp_agg.GROUP_NAMES, '') AS GROUP_NAMES,
    COALESCE(tkt.TICKET_COUNT, 0) AS TICKET_COUNT,
    tkt.LAST_ACTIVE_AT
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS a
LEFT JOIN (
    SELECT
        ag.ID AS AGENT_ID,
        LISTAGG(g.NAME, ', ') WITHIN GROUP (ORDER BY g.NAME) AS GROUP_NAMES
    FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS ag,
         LATERAL FLATTEN(INPUT => PARSE_JSON(ag.GROUP_IDS)) gid
    JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_GROUPS g
        ON g.ID = gid.VALUE::NUMBER
    GROUP BY ag.ID
) grp_agg ON grp_agg.AGENT_ID = a.ID
LEFT JOIN (
    SELECT
        RESPONDER_ID,
        COUNT(*) AS TICKET_COUNT,
        MAX(TRY_TO_TIMESTAMP_NTZ(UPDATED_AT)) AS LAST_ACTIVE_AT
    FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS
    WHERE RESPONDER_ID IS NOT NULL
    GROUP BY RESPONDER_ID
) tkt ON tkt.RESPONDER_ID = a.ID;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.AGENT_EXPERTISE AS
SELECT
    a.ID AS AGENT_ID,
    PARSE_JSON(a.CONTACT):name::VARCHAR AS AGENT_NAME,
    tag.VALUE::VARCHAR AS TAG,
    COUNT(*) AS TAG_COUNT
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t
JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_AGENTS a
    ON a.ID = t.RESPONDER_ID
, LATERAL FLATTEN(INPUT => PARSE_JSON(t.TAGS)) tag
GROUP BY a.ID, PARSE_JSON(a.CONTACT):name::VARCHAR, tag.VALUE::VARCHAR;

CREATE OR REPLACE VIEW SNOWFLAKE_INTELLIGENCE.ANALYTICS.GROUP_WORKLOAD AS
SELECT
    g.ID AS GROUP_ID,
    g.NAME AS GROUP_NAME,
    COUNT(DISTINCT t.RESPONDER_ID) AS ACTIVE_AGENTS,
    COUNT(t.ID) AS TOTAL_TICKETS,
    COUNT(CASE WHEN t.STATUS IN (2, 3) THEN 1 END) AS OPEN_TICKETS,
    CASE
        WHEN COUNT(DISTINCT t.RESPONDER_ID) > 0
        THEN ROUND(COUNT(t.ID) / COUNT(DISTINCT t.RESPONDER_ID), 0)
        ELSE 0
    END AS AVG_TICKETS_PER_AGENT
FROM SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_GROUPS g
LEFT JOIN SNOWFLAKE_INTELLIGENCE.RAW.FRESHDESK_TICKETS t
    ON t.GROUP_ID = g.ID
GROUP BY g.ID, g.NAME;
